version: "3.4"
services:
  go-shorts:
    build:
      context: .
      dockerfile: "build/package/Dockerfile"
    ports:
      - "3000:3000"
    entrypoint: "./main"
    networks:
      - shared
  test:
    build:
      context: .
      dockerfile: "build/package/Dockerfile"
      target: builder
    entrypoint: 'go test ./... -coverpkg=./... -coverprofile=coverage.out'

networks: 
  shared: